spring:
  application:
    name: bank-cards-api

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900 # 15m
    refreshTokenExpiration: 604800 # 7d

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/embank}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    liquibase: INFO
    com.embank: DEBUG